/*
FIRST: Create a visualization that displays all of the quizzes as points for one penguin. 
SECOND: Create a set of "buttons", one for each penguin. When someone presses a button, they will see an animation that will transition from the present penguin's grades to the new penguin's grades. 
NOTE: The term button is very loose here. You may use a set of image as buttons (preferred), or just a set of labeled buttons. In either case, this should be generated by d3, not by typing each one out.
*/

var appPromise = d3.json("penguins/classData.json");
appPromise.then(
    function(penguins)
        {
          //functions to call
        }) 
//brings my data in, and calls the function to draw the table.

var screen={width:400, height:500}
var margins={top:10,right:50,bottom:50,left:50}
    console.log("got margins")

var setup=function(penguins)
{
    d3.select('svg')
    .attr('width',screen.width)
    .attr('height',screen.height)
    .append('g')
    .attr('id','graph')
    .attr('transform','translate('+margins.left+','+margins.top+')');
    console.log("finished d3 alg")
    
var xScale=d3.scaleLinear()
    .domain([0,38])
    .range([0,width])
    console.log("got Xscale")


var yScale=d3.scaleLinear()
    .domain([0,100])
    .range([height,0])

//var cScale=d3.scaleOrdinal(d3.schemePastel1)

var xAxis=d3.axisBottom(xScale)
var yAxis=d3.axisLeft(yscale)
d3.select('svg')
    .append('g')
    .classed('axis',true);

d3.select(".axis")
    .append("g")
    .attr('id','xaxis')
    .attr('transform','translate('+margins.left+','(margins.top+height)+')')
    .call(xAxis)

d3.select(".axis")
    .append("g")
    .attr('id','yaxis')
    .attr('transform','translate(25,'+margins.top+')')
    .call(yAxis)
    

//drawArray(___);
}

    
    
    
    
    
    
    